// <auto-generated />
using EternaWebbApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EternaWebbApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426140242_SeedSliders")]
    partial class SeedSliders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EternaWebbApp.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ButtonLink = "#",
                            ButtonText = "Read More",
                            ImageUrl = "hero-carousel-1.jpg",
                            Name = "Welcome to Eterna",
                            SubTitle = "Modern and clean design"
                        },
                        new
                        {
                            Id = 2,
                            ButtonLink = "#",
                            ButtonText = "Get Started",
                            ImageUrl = "hero-carousel-2.jpg",
                            Name = "Build Better Websites",
                            SubTitle = "Fast, responsive and elegant"
                        },
                        new
                        {
                            Id = 3,
                            ButtonLink = "#",
                            ButtonText = "Learn More",
                            ImageUrl = "hero-carousel-3.jpg",
                            Name = "Grow Your Business",
                            SubTitle = "Solutions for your success"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
