// <auto-generated />
using EternaWebbApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EternaWebbApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426202915_mig5")]
    partial class mig5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EternaWebbApp.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "clients-1.webp"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "clients-2.webp"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "clients-3.webp"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "clients-4.webp"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "clients-5.webp"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "clients-6.webp"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "clients-7.webp"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "clients-8.webp"
                        });
                });

            modelBuilder.Entity("EternaWebbApp.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "We provide high-quality web solutions tailored to your business goals.",
                            Icon = "bi bi-briefcase",
                            Title = "Professional Service"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Clean, responsive, and user-friendly interfaces for all devices.",
                            Icon = "bi bi-gem",
                            Title = "Modern Design"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Optimized architecture and code to ensure speed and reliability.",
                            Icon = "bi bi-speedometer2",
                            Title = "Fast Performance"
                        });
                });

            modelBuilder.Entity("EternaWebbApp.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StarCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Excellent service and very professional team.",
                            StarCount = 5m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Great communication and timely delivery.",
                            StarCount = 4.5m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Highly recommended for modern web solutions.",
                            StarCount = 5m,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("EternaWebbApp.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Custom web applications built with modern, scalable technologies.",
                            Icon = "bi bi-activity",
                            Title = "Web Development"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Result-driven strategies to increase your online visibility and growth.",
                            Icon = "bi bi-broadcast",
                            Title = "Digital Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Intuitive and engaging user experiences designed for your audience.",
                            Icon = "bi bi-easel",
                            Title = "UI/UX Design"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Strong and consistent branding to make your business stand out.",
                            Icon = "bi bi-bounding-box-circles",
                            Title = "Brand Identity"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Structured planning and execution to keep projects on time and budget.",
                            Icon = "bi bi-calendar4-week",
                            Title = "Project Planning"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Expert advice to help you choose the right technical direction.",
                            Icon = "bi bi-chat-square-text",
                            Title = "Consulting"
                        });
                });

            modelBuilder.Entity("EternaWebbApp.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ButtonLink = "#",
                            ButtonText = "Read More",
                            ImageUrl = "hero-carousel-1.jpg",
                            Name = "Welcome to Eterna",
                            SubTitle = "Modern and clean design"
                        },
                        new
                        {
                            Id = 2,
                            ButtonLink = "#",
                            ButtonText = "Get Started",
                            ImageUrl = "hero-carousel-2.jpg",
                            Name = "Build Better Websites",
                            SubTitle = "Fast, responsive and elegant"
                        },
                        new
                        {
                            Id = 3,
                            ButtonLink = "#",
                            ButtonText = "Learn More",
                            ImageUrl = "hero-carousel-3.jpg",
                            Name = "Grow Your Business",
                            SubTitle = "Solutions for your success"
                        });
                });

            modelBuilder.Entity("EternaWebbApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Walter White",
                            ImageUrl = "testimonials-1.jpg",
                            Position = "Chief Executive Officer"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Sarah Johnson",
                            ImageUrl = "testimonials-2.jpg",
                            Position = "Product Manager"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "William Anderson",
                            ImageUrl = "testimonials-3.jpg",
                            Position = "CTO"
                        });
                });

            modelBuilder.Entity("EternaWebbApp.Models.Review", b =>
                {
                    b.HasOne("EternaWebbApp.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EternaWebbApp.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
