// <auto-generated />
using EternaWebbApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EternaWebbApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EternaWebbApp.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "We provide high-quality web solutions tailored to your business goals.",
                            Icon = "bi bi-briefcase",
                            Title = "Professional Service"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Clean, responsive, and user-friendly interfaces for all devices.",
                            Icon = "bi bi-gem",
                            Title = "Modern Design"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Optimized architecture and code to ensure speed and reliability.",
                            Icon = "bi bi-speedometer2",
                            Title = "Fast Performance"
                        });
                });

            modelBuilder.Entity("EternaWebbApp.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Custom web applications built with modern, scalable technologies.",
                            Icon = "bi bi-activity",
                            Title = "Web Development"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Result-driven strategies to increase your online visibility and growth.",
                            Icon = "bi bi-broadcast",
                            Title = "Digital Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Intuitive and engaging user experiences designed for your audience.",
                            Icon = "bi bi-easel",
                            Title = "UI/UX Design"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Strong and consistent branding to make your business stand out.",
                            Icon = "bi bi-bounding-box-circles",
                            Title = "Brand Identity"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Structured planning and execution to keep projects on time and budget.",
                            Icon = "bi bi-calendar4-week",
                            Title = "Project Planning"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Expert advice to help you choose the right technical direction.",
                            Icon = "bi bi-chat-square-text",
                            Title = "Consulting"
                        });
                });

            modelBuilder.Entity("EternaWebbApp.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ButtonLink = "#",
                            ButtonText = "Read More",
                            ImageUrl = "hero-carousel-1.jpg",
                            Name = "Welcome to Eterna",
                            SubTitle = "Modern and clean design"
                        },
                        new
                        {
                            Id = 2,
                            ButtonLink = "#",
                            ButtonText = "Get Started",
                            ImageUrl = "hero-carousel-2.jpg",
                            Name = "Build Better Websites",
                            SubTitle = "Fast, responsive and elegant"
                        },
                        new
                        {
                            Id = 3,
                            ButtonLink = "#",
                            ButtonText = "Learn More",
                            ImageUrl = "hero-carousel-3.jpg",
                            Name = "Grow Your Business",
                            SubTitle = "Solutions for your success"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
